// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByFNMa9xghopKLflgEgD67A5gYGkZ4rs4',
    appId: '1:317346321742:web:a425d10d6ad27ce690fa1f',
    messagingSenderId: '317346321742',
    projectId: 'eatk-f225e',
    authDomain: 'eatk-f225e.firebaseapp.com',
    storageBucket: 'eatk-f225e.firebasestorage.app',
    measurementId: 'G-D59BCV931P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMPofHaYWWcA6o1xVeproOAN-lEIy0Kzs',
    appId: '1:317346321742:android:5ca346aa4af4bc0190fa1f',
    messagingSenderId: '317346321742',
    projectId: 'eatk-f225e',
    storageBucket: 'eatk-f225e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJhbF3KQSD8QO3WiyJMvbPLmQ0IFLyfMM',
    appId: '1:317346321742:ios:be1c5981b5ba95a990fa1f',
    messagingSenderId: '317346321742',
    projectId: 'eatk-f225e',
    storageBucket: 'eatk-f225e.firebasestorage.app',
    iosBundleId: 'com.example.geoAttendanceApp',
  );
}
